apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T05:58:14Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "749"
  uid: 2f2c4187-2a95-4267-bcf7-d207bd890953
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.6.12
  clusterIPs:
  - 10.111.6.12
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30811
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
